// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

#pragma once

/** @file gdb_printers.hpp
 * @brief Embeds GDB pretty printers for reloco types into the binary.
 *
 * Including this header anywhere in a program (typically once, from the
 * translation unit containing `main`) embeds the full contents of
 * `tools/gdb/reloco_printers.py` into a `.debug_gdb_scripts` section via
 * inline assembly. When the resulting binary is loaded in GDB, GDB
 * auto-loads and runs that script, registering pretty printers for every
 * reloco container/view/smart-pointer type -- no `source` command, no
 * `<binary>-gdb.py` file, and no `sys.path` setup required.
 *
 * This still requires GDB's `auto-load safe-path` to include the path of
 * the binary containing this section (GDB disables auto-loading from
 * untrusted locations by default); see
 * https://sourceware.org/gdb/onlinedocs/gdb/Auto_002dloading-safe-path.html
 *
 * This file is generated by `tools/gdb/generate_embedded_header.py` from
 * `tools/gdb/reloco_printers.py` -- do not hand-edit it. Regenerate it
 * whenever the printer script changes.
 *
 * Embedding costs a copy of the (small) Python source in every
 * translation unit that includes this header for a *distinct* binary;
 * the `"MS"` section flags let the linker fold identical copies within
 * the same binary into one, so including it from multiple translation
 * units of the same program is free.
 *
 * The `.debug_gdb_scripts` mechanism relies on GNU-assembler inline `asm`
 * syntax and is only meaningful to GDB, so this header is a silent no-op
 * -- it defines nothing and emits no section -- on compilers other than
 * Clang/GCC (e.g. MSVC). Guarded on `__clang__`/`__GNUC__` rather than
 * platform, so it also no-ops under `clang-cl`, which defines `_MSC_VER`
 * but not GNU inline-asm syntax in its default mode.
 */

#if defined(__clang__) || defined(__GNUC__)

// clang-format off
asm(
    ".pushsection \".debug_gdb_scripts\", \"MS\",@progbits,1\n"
    ".byte 4\n" /* SECTION_SCRIPT_ID_PYTHON_TEXT */
    ".ascii \"reloco-pretty-printers.py\\n# SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>\\n#\"\n"
    ".ascii \"\\n# SPDX-License-Identifier: BSD-2-Clause\\n\\n\\\"\\\"\\\"GDB pretty printers for the reloco header-only libr\"\n"
    ".ascii \"ary.\\n\\nThis module can be used in three interchangeable ways:\\n\\n  1. Sourced directly in a running\"\n"
    ".ascii \" GDB session::\\n\\n         (gdb) source /path/to/reloco/tools/gdb/reloco_printers.py\\n\\n  2. Auto-lo\"\n"
    ".ascii \"aded for a specific binary by placing a ``<binary>-gdb.py``\\n     next to it (or anywhere on GDB'\"\n"
    ".ascii \"s auto-load path) containing::\\n\\n         import sys\\n         sys.path.insert(0, \\\"/path/to/reloco\"\n"
    ".ascii \"/tools/gdb\\\")\\n         import reloco_printers\\n         reloco_printers.register_reloco_printers()\"\n"
    ".ascii \"\\n\\n  3. Embedded directly into the binary's ``.debug_gdb_scripts`` section via\\n     ``include/rel\"\n"
    ".ascii \"oco/gdb_printers.hpp`` (see that header for details); GDB\\n     then loads and runs this exact so\"\n"
    ".ascii \"urce automatically when the binary is\\n     loaded, with no external file or path configuration r\"\n"
    ".ascii \"equired.\\n\\nIn all three cases the printers are registered against ``objfile`` (or the\\nglobal prin\"\n"
    ".ascii \"ter list, when there is no current object file) the moment this\\nmodule is loaded -- see the bott\"\n"
    ".ascii \"om of the file.\\n\\\"\\\"\\\"\\n\\ntry:\\n    import gdb\\n    import gdb.printing\\nexcept ImportError:  # pragma: \"\n"
    ".ascii \"no cover - only importable inside GDB.\\n    gdb = None\\n\\n\\ndef _read_atomic(val):\\n    \\\"\\\"\\\"Best-effor\"\n"
    ".ascii \"t read of a ``std::atomic<std::size_t>`` across libstdc++/libc++.\\\"\\\"\\\"\\n    try:\\n        return int\"\n"
    ".ascii \"(val)\\n    except (gdb.error, TypeError):\\n        pass\\n    for field in (\\\"_M_i\\\", \\\"__a_\\\"):\\n       \"\n"
    ".ascii \" try:\\n            inner = val[field]\\n        except gdb.error:\\n            continue\\n        try:\"\n"
    ".ascii \"\\n            return int(inner)\\n        except (gdb.error, TypeError):\\n            try:\\n         \"\n"
    ".ascii \"       return int(inner[\\\"__a_value\\\"])\\n            except gdb.error:\\n                continue\\n   \"\n"
    ".ascii \" return None\\n\\n\\ndef _char_pointer_string(ptr_val, length):\\n    \\\"\\\"\\\"Renders a ``CharT*`` + length p\"\n"
    ".ascii \"air the way GDB renders C strings.\\\"\\\"\\\"\\n    if length == 0:\\n        return '\\\"\\\"'\\n    try:\\n        r\"\n"
    ".ascii \"eturn ptr_val.lazy_string(length=int(length))\\n    except gdb.error:\\n        return \\\"<unreadable>\"\n"
    ".ascii \"\\\"\\n\\n\\nclass RelocoArrayPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::array<T, N>`.\\\"\\\"\\\"\\n\\n    def __ini\"\n"
    ".ascii \"t__(self, val):\\n        self.val = val\\n        self.n = int(val.type.template_argument(1))\\n\\n    \"\n"
    ".ascii \"def to_string(self):\\n        return \\\"reloco::array of length %d\\\" % self.n\\n\\n    def children(self\"\n"
    ".ascii \"):\\n        data = self.val[\\\"data_\\\"]\\n        for i in range(self.n):\\n            yield (str(i), d\"\n"
    ".ascii \"ata[i])\\n\\n    def display_hint(self):\\n        return \\\"array\\\"\\n\\n\\nclass RelocoSpanPrinter:\\n    \\\"\\\"\\\"Pr\"\n"
    ".ascii \"etty printer for `reloco::span<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n   \"\n"
    ".ascii \" def to_string(self):\\n        size = int(self.val[\\\"m_size\\\"])\\n        return \\\"reloco::span of len\"\n"
    ".ascii \"gth %d\\\" % size\\n\\n    def children(self):\\n        size = int(self.val[\\\"m_size\\\"])\\n        ptr = sel\"\n"
    ".ascii \"f.val[\\\"m_ptr\\\"]\\n        for i in range(size):\\n            yield (str(i), ptr[i])\\n\\n    def display\"\n"
    ".ascii \"_hint(self):\\n        return \\\"array\\\"\\n\\n\\nclass RelocoVectorPrinter:\\n    \\\"\\\"\\\"Pretty printer for `relo\"\n"
    ".ascii \"co::vector<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self)\"\n"
    ".ascii \":\\n        size = int(self.val[\\\"size_\\\"])\\n        cap = int(self.val[\\\"cap_\\\"])\\n        return \\\"relo\"\n"
    ".ascii \"co::vector of length %d, capacity %d\\\" % (size, cap)\\n\\n    def children(self):\\n        size = int(\"\n"
    ".ascii \"self.val[\\\"size_\\\"])\\n        data = self.val[\\\"data_\\\"]\\n        for i in range(size):\\n            yi\"\n"
    ".ascii \"eld (str(i), data[i])\\n\\n    def display_hint(self):\\n        return \\\"array\\\"\\n\\n\\nclass RelocoInlineVe\"\n"
    ".ascii \"ctorPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::inline_vector<T, Capacity>`.\\\"\\\"\\\"\\n\\n    def __init_\"\n"
    ".ascii \"_(self, val):\\n        self.val = val\\n        self.elem_type = val.type.template_argument(0)\\n\\n   \"\n"
    ".ascii \" def to_string(self):\\n        size = int(self.val[\\\"size_\\\"])\\n        cap = int(self.val.type.temp\"\n"
    ".ascii \"late_argument(1))\\n        return \\\"reloco::inline_vector of length %d, capacity %d\\\" % (size, cap)\"\n"
    ".ascii \"\\n\\n    def children(self):\\n        size = int(self.val[\\\"size_\\\"])\\n        data = self.val[\\\"storage\"\n"
    ".ascii \"_\\\"].address.cast(self.elem_type.pointer())\\n        for i in range(size):\\n            yield (str(\"\n"
    ".ascii \"i), data[i])\\n\\n    def display_hint(self):\\n        return \\\"array\\\"\\n\\n\\nclass RelocoFlatSetPrinter:\\n \"\n"
    ".ascii \"   \\\"\\\"\\\"Pretty printer for `reloco::flat_set<T, Compare>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n      \"\n"
    ".ascii \"  self.val = val\\n\\n    def to_string(self):\\n        size = int(self.val[\\\"data_\\\"][\\\"size_\\\"])\\n      \"\n"
    ".ascii \"  return \\\"reloco::flat_set of length %d\\\" % size\\n\\n    def children(self):\\n        vec = self.val[\"\n"
    ".ascii \"\\\"data_\\\"]\\n        size = int(vec[\\\"size_\\\"])\\n        data = vec[\\\"data_\\\"]\\n        for i in range(siz\"\n"
    ".ascii \"e):\\n            yield (str(i), data[i])\\n\\n    def display_hint(self):\\n        return \\\"array\\\"\\n\\n\\ncl\"\n"
    ".ascii \"ass RelocoStringPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::basic_string<CharT, TraitsT>`.\\\"\\\"\\\"\\n\\n \"\n"
    ".ascii \"   def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        size = self\"\n"
    ".ascii \".val[\\\"size_\\\"]\\n        return _char_pointer_string(self.val[\\\"data_\\\"], size)\\n\\n    def display_hint\"\n"
    ".ascii \"(self):\\n        return \\\"string\\\"\\n\\n\\nclass RelocoStringViewPrinter:\\n    \\\"\\\"\\\"Pretty printer for `relo\"\n"
    ".ascii \"co::basic_string_view<CharT, TraitsT>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\"\n"
    ".ascii \"\\n    def to_string(self):\\n        size = self.val[\\\"size_\\\"]\\n        return _char_pointer_string(s\"\n"
    ".ascii \"elf.val[\\\"data_\\\"], size)\\n\\n    def display_hint(self):\\n        return \\\"string\\\"\\n\\n\\nclass RelocoInlin\"\n"
    ".ascii \"eStringPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::basic_inline_string<Capacity, CharT, TraitsT>\"\n"
    ".ascii \"`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        siz\"\n"
    ".ascii \"e = self.val[\\\"size_\\\"]\\n        return _char_pointer_string(self.val[\\\"data_\\\"], size)\\n\\n    def disp\"\n"
    ".ascii \"lay_hint(self):\\n        return \\\"string\\\"\\n\\n\\nclass RelocoOptionalPrinter:\\n    \\\"\\\"\\\"Pretty printer for\"\n"
    ".ascii \" `reloco::optional<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_stri\"\n"
    ".ascii \"ng(self):\\n        if not bool(self.val[\\\"has_value_\\\"]):\\n            return \\\"reloco::optional [no \"\n"
    ".ascii \"value]\\\"\\n        return None\\n\\n    def children(self):\\n        if bool(self.val[\\\"has_value_\\\"]):\\n  \"\n"
    ".ascii \"          yield (\\\"value\\\", self.val[\\\"value_\\\"])\\n\\n\\nclass RelocoExpectedPrinter:\\n    \\\"\\\"\\\"Pretty print\"\n"
    ".ascii \"er for `reloco::expected<T, E>` (and its `void` specialization).\\\"\\\"\\\"\\n\\n    def __init__(self, val)\"\n"
    ".ascii \":\\n        self.val = val\\n\\n    def _has_value(self):\\n        return bool(self.val[\\\"m_has_value\\\"])\"\n"
    ".ascii \"\\n\\n    def to_string(self):\\n        if self._has_value():\\n            try:\\n                self.v\"\n"
    ".ascii \"al[\\\"m_value\\\"]\\n            except gdb.error:\\n                return \\\"reloco::expected<void, ...> \"\n"
    ".ascii \"[value]\\\"\\n            return None\\n        return None\\n\\n    def children(self):\\n        if self._h\"\n"
    ".ascii \"as_value():\\n            try:\\n                yield (\\\"value\\\", self.val[\\\"m_value\\\"])\\n            ex\"\n"
    ".ascii \"cept gdb.error:\\n                pass\\n        else:\\n            yield (\\\"error\\\", self.val[\\\"m_error\"\n"
    ".ascii \"\\\"])\\n\\n\\nclass RelocoUniquePtrPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::unique_ptr<T>`.\\\"\\\"\\\"\\n\\n    d\"\n"
    ".ascii \"ef __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        ptr = self.val[\"\n"
    ".ascii \"\\\"ptr_\\\"]\\n        if int(ptr) == 0:\\n            return \\\"reloco::unique_ptr [empty]\\\"\\n        return\"\n"
    ".ascii \" \\\"reloco::unique_ptr = %s\\\" % str(ptr)\\n\\n    def children(self):\\n        ptr = self.val[\\\"ptr_\\\"]\\n  \"\n"
    ".ascii \"      if int(ptr) != 0:\\n            yield (\\\"get()\\\", ptr.dereference())\\n\\n\\nclass RelocoValuePtrPri\"\n"
    ".ascii \"nter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::value_ptr<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n       \"\n"
    ".ascii \" self.val = val\\n\\n    def to_string(self):\\n        ptr = self.val[\\\"ptr_\\\"]\\n        if int(ptr) == \"\n"
    ".ascii \"0:\\n            return \\\"reloco::value_ptr [empty]\\\"\\n        return \\\"reloco::value_ptr = %s\\\" % str(\"\n"
    ".ascii \"ptr)\\n\\n    def children(self):\\n        ptr = self.val[\\\"ptr_\\\"]\\n        if int(ptr) != 0:\\n         \"\n"
    ".ascii \"   yield (\\\"get()\\\", ptr.dereference())\\n\\n\\nclass RelocoValueRefPrinter:\\n    \\\"\\\"\\\"Pretty printer for `\"\n"
    ".ascii \"reloco::value_ref<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_strin\"\n"
    ".ascii \"g(self):\\n        ptr = self.val[\\\"m_ptr\\\"][\\\"ptr_\\\"]\\n        return \\\"reloco::value_ref -> %s\\\" % str(\"\n"
    ".ascii \"ptr)\\n\\n    def children(self):\\n        ptr = self.val[\\\"m_ptr\\\"][\\\"ptr_\\\"]\\n        if int(ptr) != 0:\\n\"\n"
    ".ascii \"            yield (\\\"value\\\", ptr.dereference())\\n\\n\\nclass RelocoCheckedValuePrinter:\\n    \\\"\\\"\\\"Pretty \"\n"
    ".ascii \"printer for `reloco::checked_value<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\"\n"
    ".ascii \"\\n    def to_string(self):\\n        if bool(self.val[\\\"moved_from_\\\"]):\\n            return \\\"reloco::\"\n"
    ".ascii \"checked_value [moved-from]\\\"\\n        return None\\n\\n    def children(self):\\n        if not bool(sel\"\n"
    ".ascii \"f.val[\\\"moved_from_\\\"]):\\n            yield (\\\"value\\\", self.val[\\\"value_\\\"])\\n\\n\\nclass _RelocoSharedPtrP\"\n"
    ".ascii \"rinterBase:\\n    \\\"\\\"\\\"Shared implementation for `reloco::shared_ptr<T>`/`reloco::weak_ptr<T>`.\\\"\\\"\\\"\\n\\n\"\n"
    ".ascii \"    is_weak = False\\n    kind = \\\"shared_ptr\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\"\n"
    ".ascii \"\\n\\n    def to_string(self):\\n        ptr = self.val[\\\"ptr_\\\"]\\n        block = self.val[\\\"block_\\\"]\\n   \"\n"
    ".ascii \"     if int(block) == 0:\\n            return \\\"reloco::%s [empty]\\\" % self.kind\\n        shared = _r\"\n"
    ".ascii \"ead_atomic(block.dereference()[\\\"shared_count_\\\"])\\n        weak = _read_atomic(block.dereference()\"\n"
    ".ascii \"[\\\"weak_count_\\\"])\\n        return \\\"reloco::%s = %s (use_count %s, weak_count %s)\\\" % (\\n            \"\n"
    ".ascii \"self.kind,\\n            str(ptr),\\n            \\\"?\\\" if shared is None else shared,\\n            \\\"?\\\" \"\n"
    ".ascii \"if weak is None else weak,\\n        )\\n\\n    def children(self):\\n        ptr = self.val[\\\"ptr_\\\"]\\n   \"\n"
    ".ascii \"     block = self.val[\\\"block_\\\"]\\n        if int(block) != 0 and int(ptr) != 0 and not self.is_wea\"\n"
    ".ascii \"k:\\n            yield (\\\"get()\\\", ptr.dereference())\\n\\n\\nclass RelocoSharedPtrPrinter(_RelocoSharedPt\"\n"
    ".ascii \"rPrinterBase):\\n    \\\"\\\"\\\"Pretty printer for `reloco::shared_ptr<T>`.\\\"\\\"\\\"\\n\\n    is_weak = False\\n    ki\"\n"
    ".ascii \"nd = \\\"shared_ptr\\\"\\n\\n\\nclass RelocoWeakPtrPrinter(_RelocoSharedPtrPrinterBase):\\n    \\\"\\\"\\\"Pretty print\"\n"
    ".ascii \"er for `reloco::weak_ptr<T>`.\\\"\\\"\\\"\\n\\n    is_weak = True\\n    kind = \\\"weak_ptr\\\"\\n\\n\\nclass RelocoFunctio\"\n"
    ".ascii \"nRefPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::function_ref<Signature>`.\\\"\\\"\\\"\\n\\n    def __init__(s\"\n"
    ".ascii \"elf, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        callback = self.val[\\\"callbac\"\n"
    ".ascii \"k_\\\"]\\n        return \\\"reloco::function_ref bound at %s\\\" % str(callback)\\n\\n\\ndef _build_pretty_print\"\n"
    ".ascii \"er():\\n    pp = gdb.printing.RegexpCollectionPrettyPrinter(\\\"reloco\\\")\\n    pp.add_printer(\\\"reloco::\"\n"
    ".ascii \"array\\\", r\\\"^reloco::array<.*>$\\\", RelocoArrayPrinter)\\n    pp.add_printer(\\\"reloco::span\\\", r\\\"^reloco\"\n"
    ".ascii \"::span<.*>$\\\", RelocoSpanPrinter)\\n    pp.add_printer(\\\"reloco::vector\\\", r\\\"^reloco::vector<.*>$\\\", R\"\n"
    ".ascii \"elocoVectorPrinter)\\n    pp.add_printer(\\\"reloco::inline_vector\\\", r\\\"^reloco::inline_vector<.*>$\\\", \"\n"
    ".ascii \"RelocoInlineVectorPrinter)\\n    pp.add_printer(\\\"reloco::flat_set\\\", r\\\"^reloco::flat_set<.*>$\\\", Rel\"\n"
    ".ascii \"ocoFlatSetPrinter)\\n    pp.add_printer(\\\"reloco::basic_string\\\", r\\\"^reloco::basic_string<.*>$\\\", Rel\"\n"
    ".ascii \"ocoStringPrinter)\\n    pp.add_printer(\\\"reloco::basic_string_view\\\", r\\\"^reloco::basic_string_view<.\"\n"
    ".ascii \"*>$\\\", RelocoStringViewPrinter)\\n    pp.add_printer(\\\"reloco::basic_inline_string\\\", r\\\"^reloco::basi\"\n"
    ".ascii \"c_inline_string<.*>$\\\", RelocoInlineStringPrinter)\\n    pp.add_printer(\\\"reloco::optional\\\", r\\\"^relo\"\n"
    ".ascii \"co::optional<.*>$\\\", RelocoOptionalPrinter)\\n    pp.add_printer(\\\"reloco::expected\\\", r\\\"^reloco::exp\"\n"
    ".ascii \"ected<.*>$\\\", RelocoExpectedPrinter)\\n    pp.add_printer(\\\"reloco::unique_ptr\\\", r\\\"^reloco::unique_p\"\n"
    ".ascii \"tr<.*>$\\\", RelocoUniquePtrPrinter)\\n    pp.add_printer(\\\"reloco::value_ptr\\\", r\\\"^reloco::value_ptr<.\"\n"
    ".ascii \"*>$\\\", RelocoValuePtrPrinter)\\n    pp.add_printer(\\\"reloco::value_ref\\\", r\\\"^reloco::value_ref<.*>$\\\",\"\n"
    ".ascii \" RelocoValueRefPrinter)\\n    pp.add_printer(\\\"reloco::checked_value\\\", r\\\"^reloco::checked_value<.*>\"\n"
    ".ascii \"$\\\", RelocoCheckedValuePrinter)\\n    pp.add_printer(\\\"reloco::shared_ptr\\\", r\\\"^reloco::shared_ptr<.*\"\n"
    ".ascii \">$\\\", RelocoSharedPtrPrinter)\\n    pp.add_printer(\\\"reloco::weak_ptr\\\", r\\\"^reloco::weak_ptr<.*>$\\\", R\"\n"
    ".ascii \"elocoWeakPtrPrinter)\\n    pp.add_printer(\\\"reloco::function_ref\\\", r\\\"^reloco::function_ref<.*>$\\\", R\"\n"
    ".ascii \"elocoFunctionRefPrinter)\\n    return pp\\n\\n\\ndef register_reloco_printers(objfile=None):\\n    \\\"\\\"\\\"Regi\"\n"
    ".ascii \"sters the reloco pretty printers with GDB.\\n\\n    Idempotent: re-registering (e.g. because this mo\"\n"
    ".ascii \"dule was sourced twice,\\n    or embedded in several object files) simply replaces the previous\\n  \"\n"
    ".ascii \"  registration under the same name.\\n    \\\"\\\"\\\"\\n    if gdb is None:\\n        return\\n\\n    target = obj\"\n"
    ".ascii \"file if objfile is not None else gdb\\n    gdb.printing.register_pretty_printer(target, _build_pre\"\n"
    ".ascii \"tty_printer(), replace=True)\\n\\n\\nif gdb is not None:\\n    register_reloco_printers(gdb.current_objf\"\n"
    ".ascii \"ile())\\n\"\n"
    ".byte 0\n"
    ".popsection\n"
);
// clang-format on

#endif // defined(__clang__) || defined(__GNUC__)
