// SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>
//
// SPDX-License-Identifier: BSD-2-Clause

#pragma once

/** @file gdb_printers.hpp
 * @brief Embeds GDB pretty printers for reloco types into the binary.
 *
 * Including this header anywhere in a program (typically once, from the
 * translation unit containing `main`) embeds the full contents of
 * `tools/gdb/reloco_printers.py` into a `.debug_gdb_scripts` section via
 * inline assembly. When the resulting binary is loaded in GDB, GDB
 * auto-loads and runs that script, registering pretty printers for every
 * reloco container/view/smart-pointer type -- no `source` command, no
 * `<binary>-gdb.py` file, and no `sys.path` setup required.
 *
 * This still requires GDB's `auto-load safe-path` to include the path of
 * the binary containing this section (GDB disables auto-loading from
 * untrusted locations by default); see
 * https://sourceware.org/gdb/onlinedocs/gdb/Auto_002dloading-safe-path.html
 *
 * This file is generated by `tools/gdb/generate_embedded_header.py` from
 * `tools/gdb/reloco_printers.py` -- do not hand-edit it. Regenerate it
 * whenever the printer script changes.
 *
 * Embedding costs a copy of the (small) Python source in every
 * translation unit that includes this header for a *distinct* binary;
 * the `"MS"` section flags let the linker fold identical copies within
 * the same binary into one, so including it from multiple translation
 * units of the same program is free.
 *
 * The `.debug_gdb_scripts` mechanism relies on GNU-assembler inline `asm`
 * syntax and is only meaningful to GDB, so this header is a silent no-op
 * -- it defines nothing and emits no section -- on compilers other than
 * Clang/GCC (e.g. MSVC). Guarded on `__clang__`/`__GNUC__` rather than
 * platform, so it also no-ops under `clang-cl`, which defines `_MSC_VER`
 * but not GNU inline-asm syntax in its default mode.
 */

#if defined(__clang__) || defined(__GNUC__)

// clang-format off
asm(
    ".pushsection \".debug_gdb_scripts\", \"MS\",@progbits,1\n"
    ".byte 4\n" /* SECTION_SCRIPT_ID_PYTHON_TEXT */
    ".ascii \"reloco-pretty-printers.py\\n# SPDX-FileCopyrightText: 2026 Jarosław Pelczar <jarek@jpelczar.com>\\n#\"\n"
    ".ascii \"\\n# SPDX-License-Identifier: BSD-2-Clause\\n\\n\\\"\\\"\\\"GDB pretty printers for the reloco header-only libr\"\n"
    ".ascii \"ary.\\n\\nThis module can be used in three interchangeable ways:\\n\\n  1. Sourced directly in a running\"\n"
    ".ascii \" GDB session::\\n\\n         (gdb) source /path/to/reloco/tools/gdb/reloco_printers.py\\n\\n  2. Auto-lo\"\n"
    ".ascii \"aded for a specific binary by placing a ``<binary>-gdb.py``\\n     next to it (or anywhere on GDB'\"\n"
    ".ascii \"s auto-load path) containing::\\n\\n         import sys\\n         sys.path.insert(0, \\\"/path/to/reloco\"\n"
    ".ascii \"/tools/gdb\\\")\\n         import reloco_printers\\n         reloco_printers.register_reloco_printers()\"\n"
    ".ascii \"\\n\\n  3. Embedded directly into the binary's ``.debug_gdb_scripts`` section via\\n     ``include/rel\"\n"
    ".ascii \"oco/gdb_printers.hpp`` (see that header for details); GDB\\n     then loads and runs this exact so\"\n"
    ".ascii \"urce automatically when the binary is\\n     loaded, with no external file or path configuration r\"\n"
    ".ascii \"equired.\\n\\nIn all three cases the printers are registered against ``objfile`` (or the\\nglobal prin\"\n"
    ".ascii \"ter list, when there is no current object file) the moment this\\nmodule is loaded -- see the bott\"\n"
    ".ascii \"om of the file.\\n\\\"\\\"\\\"\\n\\ntry:\\n    import gdb\\n    import gdb.printing\\nexcept ImportError:  # pragma: \"\n"
    ".ascii \"no cover - only importable inside GDB.\\n    gdb = None\\n\\n\\ndef _read_atomic(val):\\n    \\\"\\\"\\\"Best-effor\"\n"
    ".ascii \"t read of a ``std::atomic<std::size_t>`` across libstdc++/libc++.\\\"\\\"\\\"\\n    try:\\n        return int\"\n"
    ".ascii \"(val)\\n    except (gdb.error, TypeError):\\n        pass\\n    for field in (\\\"_M_i\\\", \\\"__a_\\\"):\\n       \"\n"
    ".ascii \" try:\\n            inner = val[field]\\n        except gdb.error:\\n            continue\\n        try:\"\n"
    ".ascii \"\\n            return int(inner)\\n        except (gdb.error, TypeError):\\n            try:\\n         \"\n"
    ".ascii \"       return int(inner[\\\"__a_value\\\"])\\n            except gdb.error:\\n                continue\\n   \"\n"
    ".ascii \" return None\\n\\n\\ndef _char_pointer_string(ptr_val, length):\\n    \\\"\\\"\\\"Renders a ``CharT*`` + length p\"\n"
    ".ascii \"air the way GDB renders C strings.\\\"\\\"\\\"\\n    if length == 0:\\n        return '\\\"\\\"'\\n    try:\\n        r\"\n"
    ".ascii \"eturn ptr_val.lazy_string(length=int(length))\\n    except gdb.error:\\n        return \\\"<unreadable>\"\n"
    ".ascii \"\\\"\\n\\n\\nclass RelocoArrayPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::array<T, N>`.\\\"\\\"\\\"\\n\\n    def __ini\"\n"
    ".ascii \"t__(self, val):\\n        self.val = val\\n        self.n = int(val.type.template_argument(1))\\n\\n    \"\n"
    ".ascii \"def to_string(self):\\n        return \\\"reloco::array of length %d\\\" % self.n\\n\\n    def children(self\"\n"
    ".ascii \"):\\n        data = self.val[\\\"data_\\\"]\\n        for i in range(self.n):\\n            yield (str(i), d\"\n"
    ".ascii \"ata[i])\\n\\n    def display_hint(self):\\n        return \\\"array\\\"\\n\\n\\nclass RelocoSpanPrinter:\\n    \\\"\\\"\\\"Pr\"\n"
    ".ascii \"etty printer for `reloco::span<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n   \"\n"
    ".ascii \" def to_string(self):\\n        size = int(self.val[\\\"m_size\\\"])\\n        return \\\"reloco::span of len\"\n"
    ".ascii \"gth %d\\\" % size\\n\\n    def children(self):\\n        size = int(self.val[\\\"m_size\\\"])\\n        ptr = sel\"\n"
    ".ascii \"f.val[\\\"m_ptr\\\"]\\n        for i in range(size):\\n            yield (str(i), ptr[i])\\n\\n    def display\"\n"
    ".ascii \"_hint(self):\\n        return \\\"array\\\"\\n\\n\\nclass RelocoVectorPrinter:\\n    \\\"\\\"\\\"Pretty printer for `relo\"\n"
    ".ascii \"co::vector<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self)\"\n"
    ".ascii \":\\n        size = int(self.val[\\\"size_\\\"])\\n        cap = int(self.val[\\\"cap_\\\"])\\n        return \\\"relo\"\n"
    ".ascii \"co::vector of length %d, capacity %d\\\" % (size, cap)\\n\\n    def children(self):\\n        size = int(\"\n"
    ".ascii \"self.val[\\\"size_\\\"])\\n        data = self.val[\\\"data_\\\"]\\n        for i in range(size):\\n            yi\"\n"
    ".ascii \"eld (str(i), data[i])\\n\\n    def display_hint(self):\\n        return \\\"array\\\"\\n\\n\\nclass RelocoFlatSetP\"\n"
    ".ascii \"rinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::flat_set<T, Compare>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val\"\n"
    ".ascii \"):\\n        self.val = val\\n\\n    def to_string(self):\\n        size = int(self.val[\\\"data_\\\"][\\\"size_\\\"\"\n"
    ".ascii \"])\\n        return \\\"reloco::flat_set of length %d\\\" % size\\n\\n    def children(self):\\n        vec = \"\n"
    ".ascii \"self.val[\\\"data_\\\"]\\n        size = int(vec[\\\"size_\\\"])\\n        data = vec[\\\"data_\\\"]\\n        for i in \"\n"
    ".ascii \"range(size):\\n            yield (str(i), data[i])\\n\\n    def display_hint(self):\\n        return \\\"ar\"\n"
    ".ascii \"ray\\\"\\n\\n\\nclass RelocoStringPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::basic_string<CharT, TraitsT\"\n"
    ".ascii \">`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        si\"\n"
    ".ascii \"ze = self.val[\\\"size_\\\"]\\n        return _char_pointer_string(self.val[\\\"data_\\\"], size)\\n\\n    def dis\"\n"
    ".ascii \"play_hint(self):\\n        return \\\"string\\\"\\n\\n\\nclass RelocoStringViewPrinter:\\n    \\\"\\\"\\\"Pretty printer \"\n"
    ".ascii \"for `reloco::basic_string_view<CharT, TraitsT>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.v\"\n"
    ".ascii \"al = val\\n\\n    def to_string(self):\\n        size = self.val[\\\"size_\\\"]\\n        return _char_pointer\"\n"
    ".ascii \"_string(self.val[\\\"data_\\\"], size)\\n\\n    def display_hint(self):\\n        return \\\"string\\\"\\n\\n\\nclass Re\"\n"
    ".ascii \"locoInlineStringPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::basic_inline_string<Capacity, CharT,\"\n"
    ".ascii \" TraitsT>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n  \"\n"
    ".ascii \"      size = self.val[\\\"size_\\\"]\\n        return _char_pointer_string(self.val[\\\"data_\\\"], size)\\n\\n   \"\n"
    ".ascii \" def display_hint(self):\\n        return \\\"string\\\"\\n\\n\\nclass RelocoOptionalPrinter:\\n    \\\"\\\"\\\"Pretty pr\"\n"
    ".ascii \"inter for `reloco::optional<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    de\"\n"
    ".ascii \"f to_string(self):\\n        if not bool(self.val[\\\"has_value_\\\"]):\\n            return \\\"reloco::opti\"\n"
    ".ascii \"onal [no value]\\\"\\n        return None\\n\\n    def children(self):\\n        if bool(self.val[\\\"has_valu\"\n"
    ".ascii \"e_\\\"]):\\n            yield (\\\"value\\\", self.val[\\\"value_\\\"])\\n\\n\\nclass RelocoExpectedPrinter:\\n    \\\"\\\"\\\"Pre\"\n"
    ".ascii \"tty printer for `reloco::expected<T, E>` (and its `void` specialization).\\\"\\\"\\\"\\n\\n    def __init__(s\"\n"
    ".ascii \"elf, val):\\n        self.val = val\\n\\n    def _has_value(self):\\n        return bool(self.val[\\\"m_has\"\n"
    ".ascii \"_value\\\"])\\n\\n    def to_string(self):\\n        if self._has_value():\\n            try:\\n             \"\n"
    ".ascii \"   self.val[\\\"m_value\\\"]\\n            except gdb.error:\\n                return \\\"reloco::expected<vo\"\n"
    ".ascii \"id, ...> [value]\\\"\\n            return None\\n        return None\\n\\n    def children(self):\\n        i\"\n"
    ".ascii \"f self._has_value():\\n            try:\\n                yield (\\\"value\\\", self.val[\\\"m_value\\\"])\\n     \"\n"
    ".ascii \"       except gdb.error:\\n                pass\\n        else:\\n            yield (\\\"error\\\", self.val\"\n"
    ".ascii \"[\\\"m_error\\\"])\\n\\n\\nclass RelocoUniquePtrPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::unique_ptr<T>`.\\\"\"\n"
    ".ascii \"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        ptr = \"\n"
    ".ascii \"self.val[\\\"ptr_\\\"]\\n        if int(ptr) == 0:\\n            return \\\"reloco::unique_ptr [empty]\\\"\\n     \"\n"
    ".ascii \"   return \\\"reloco::unique_ptr = %s\\\" % str(ptr)\\n\\n    def children(self):\\n        ptr = self.val[\\\"\"\n"
    ".ascii \"ptr_\\\"]\\n        if int(ptr) != 0:\\n            yield (\\\"get()\\\", ptr.dereference())\\n\\n\\nclass RelocoVa\"\n"
    ".ascii \"luePtrPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::value_ptr<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val)\"\n"
    ".ascii \":\\n        self.val = val\\n\\n    def to_string(self):\\n        ptr = self.val[\\\"ptr_\\\"]\\n        if int\"\n"
    ".ascii \"(ptr) == 0:\\n            return \\\"reloco::value_ptr [empty]\\\"\\n        return \\\"reloco::value_ptr = %\"\n"
    ".ascii \"s\\\" % str(ptr)\\n\\n    def children(self):\\n        ptr = self.val[\\\"ptr_\\\"]\\n        if int(ptr) != 0:\\n\"\n"
    ".ascii \"            yield (\\\"get()\\\", ptr.dereference())\\n\\n\\nclass RelocoValueRefPrinter:\\n    \\\"\\\"\\\"Pretty prin\"\n"
    ".ascii \"ter for `reloco::value_ref<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.val = val\\n\\n    def\"\n"
    ".ascii \" to_string(self):\\n        ptr = self.val[\\\"m_ptr\\\"][\\\"ptr_\\\"]\\n        return \\\"reloco::value_ref -> %\"\n"
    ".ascii \"s\\\" % str(ptr)\\n\\n    def children(self):\\n        ptr = self.val[\\\"m_ptr\\\"][\\\"ptr_\\\"]\\n        if int(pt\"\n"
    ".ascii \"r) != 0:\\n            yield (\\\"value\\\", ptr.dereference())\\n\\n\\nclass RelocoCheckedValuePrinter:\\n    \\\"\"\n"
    ".ascii \"\\\"\\\"Pretty printer for `reloco::checked_value<T>`.\\\"\\\"\\\"\\n\\n    def __init__(self, val):\\n        self.v\"\n"
    ".ascii \"al = val\\n\\n    def to_string(self):\\n        if bool(self.val[\\\"moved_from_\\\"]):\\n            return \"\n"
    ".ascii \"\\\"reloco::checked_value [moved-from]\\\"\\n        return None\\n\\n    def children(self):\\n        if not\"\n"
    ".ascii \" bool(self.val[\\\"moved_from_\\\"]):\\n            yield (\\\"value\\\", self.val[\\\"value_\\\"])\\n\\n\\nclass _RelocoS\"\n"
    ".ascii \"haredPtrPrinterBase:\\n    \\\"\\\"\\\"Shared implementation for `reloco::shared_ptr<T>`/`reloco::weak_ptr<\"\n"
    ".ascii \"T>`.\\\"\\\"\\\"\\n\\n    is_weak = False\\n    kind = \\\"shared_ptr\\\"\\n\\n    def __init__(self, val):\\n        self.\"\n"
    ".ascii \"val = val\\n\\n    def to_string(self):\\n        ptr = self.val[\\\"ptr_\\\"]\\n        block = self.val[\\\"blo\"\n"
    ".ascii \"ck_\\\"]\\n        if int(block) == 0:\\n            return \\\"reloco::%s [empty]\\\" % self.kind\\n        sh\"\n"
    ".ascii \"ared = _read_atomic(block.dereference()[\\\"shared_count_\\\"])\\n        weak = _read_atomic(block.dere\"\n"
    ".ascii \"ference()[\\\"weak_count_\\\"])\\n        return \\\"reloco::%s = %s (use_count %s, weak_count %s)\\\" % (\\n   \"\n"
    ".ascii \"         self.kind,\\n            str(ptr),\\n            \\\"?\\\" if shared is None else shared,\\n       \"\n"
    ".ascii \"     \\\"?\\\" if weak is None else weak,\\n        )\\n\\n    def children(self):\\n        ptr = self.val[\\\"p\"\n"
    ".ascii \"tr_\\\"]\\n        block = self.val[\\\"block_\\\"]\\n        if int(block) != 0 and int(ptr) != 0 and not se\"\n"
    ".ascii \"lf.is_weak:\\n            yield (\\\"get()\\\", ptr.dereference())\\n\\n\\nclass RelocoSharedPtrPrinter(_Reloc\"\n"
    ".ascii \"oSharedPtrPrinterBase):\\n    \\\"\\\"\\\"Pretty printer for `reloco::shared_ptr<T>`.\\\"\\\"\\\"\\n\\n    is_weak = Fal\"\n"
    ".ascii \"se\\n    kind = \\\"shared_ptr\\\"\\n\\n\\nclass RelocoWeakPtrPrinter(_RelocoSharedPtrPrinterBase):\\n    \\\"\\\"\\\"Pre\"\n"
    ".ascii \"tty printer for `reloco::weak_ptr<T>`.\\\"\\\"\\\"\\n\\n    is_weak = True\\n    kind = \\\"weak_ptr\\\"\\n\\n\\nclass Relo\"\n"
    ".ascii \"coFunctionRefPrinter:\\n    \\\"\\\"\\\"Pretty printer for `reloco::function_ref<Signature>`.\\\"\\\"\\\"\\n\\n    def _\"\n"
    ".ascii \"_init__(self, val):\\n        self.val = val\\n\\n    def to_string(self):\\n        callback = self.val\"\n"
    ".ascii \"[\\\"callback_\\\"]\\n        return \\\"reloco::function_ref bound at %s\\\" % str(callback)\\n\\n\\ndef _build_pre\"\n"
    ".ascii \"tty_printer():\\n    pp = gdb.printing.RegexpCollectionPrettyPrinter(\\\"reloco\\\")\\n    pp.add_printer(\"\n"
    ".ascii \"\\\"reloco::array\\\", r\\\"^reloco::array<.*>$\\\", RelocoArrayPrinter)\\n    pp.add_printer(\\\"reloco::span\\\", \"\n"
    ".ascii \"r\\\"^reloco::span<.*>$\\\", RelocoSpanPrinter)\\n    pp.add_printer(\\\"reloco::vector\\\", r\\\"^reloco::vector\"\n"
    ".ascii \"<.*>$\\\", RelocoVectorPrinter)\\n    pp.add_printer(\\\"reloco::flat_set\\\", r\\\"^reloco::flat_set<.*>$\\\", R\"\n"
    ".ascii \"elocoFlatSetPrinter)\\n    pp.add_printer(\\\"reloco::basic_string\\\", r\\\"^reloco::basic_string<.*>$\\\", R\"\n"
    ".ascii \"elocoStringPrinter)\\n    pp.add_printer(\\\"reloco::basic_string_view\\\", r\\\"^reloco::basic_string_view\"\n"
    ".ascii \"<.*>$\\\", RelocoStringViewPrinter)\\n    pp.add_printer(\\\"reloco::basic_inline_string\\\", r\\\"^reloco::ba\"\n"
    ".ascii \"sic_inline_string<.*>$\\\", RelocoInlineStringPrinter)\\n    pp.add_printer(\\\"reloco::optional\\\", r\\\"^re\"\n"
    ".ascii \"loco::optional<.*>$\\\", RelocoOptionalPrinter)\\n    pp.add_printer(\\\"reloco::expected\\\", r\\\"^reloco::e\"\n"
    ".ascii \"xpected<.*>$\\\", RelocoExpectedPrinter)\\n    pp.add_printer(\\\"reloco::unique_ptr\\\", r\\\"^reloco::unique\"\n"
    ".ascii \"_ptr<.*>$\\\", RelocoUniquePtrPrinter)\\n    pp.add_printer(\\\"reloco::value_ptr\\\", r\\\"^reloco::value_ptr\"\n"
    ".ascii \"<.*>$\\\", RelocoValuePtrPrinter)\\n    pp.add_printer(\\\"reloco::value_ref\\\", r\\\"^reloco::value_ref<.*>$\"\n"
    ".ascii \"\\\", RelocoValueRefPrinter)\\n    pp.add_printer(\\\"reloco::checked_value\\\", r\\\"^reloco::checked_value<.\"\n"
    ".ascii \"*>$\\\", RelocoCheckedValuePrinter)\\n    pp.add_printer(\\\"reloco::shared_ptr\\\", r\\\"^reloco::shared_ptr<\"\n"
    ".ascii \".*>$\\\", RelocoSharedPtrPrinter)\\n    pp.add_printer(\\\"reloco::weak_ptr\\\", r\\\"^reloco::weak_ptr<.*>$\\\",\"\n"
    ".ascii \" RelocoWeakPtrPrinter)\\n    pp.add_printer(\\\"reloco::function_ref\\\", r\\\"^reloco::function_ref<.*>$\\\",\"\n"
    ".ascii \" RelocoFunctionRefPrinter)\\n    return pp\\n\\n\\ndef register_reloco_printers(objfile=None):\\n    \\\"\\\"\\\"Re\"\n"
    ".ascii \"gisters the reloco pretty printers with GDB.\\n\\n    Idempotent: re-registering (e.g. because this \"\n"
    ".ascii \"module was sourced twice,\\n    or embedded in several object files) simply replaces the previous\\n\"\n"
    ".ascii \"    registration under the same name.\\n    \\\"\\\"\\\"\\n    if gdb is None:\\n        return\\n\\n    target = o\"\n"
    ".ascii \"bjfile if objfile is not None else gdb\\n    gdb.printing.register_pretty_printer(target, _build_p\"\n"
    ".ascii \"retty_printer(), replace=True)\\n\\n\\nif gdb is not None:\\n    register_reloco_printers(gdb.current_ob\"\n"
    ".ascii \"jfile())\\n\"\n"
    ".byte 0\n"
    ".popsection\n"
);
// clang-format on

#endif // defined(__clang__) || defined(__GNUC__)
